### PR TITLE
Added documentation for HP Vertica and Redshift

### PR DESCRIPTION
**Pull request by nathanvick**
Axel, I added documentation for Vertica and Redshift, per your request last week. This documentation corresponds to the database support added in the following pull requests:

https://github.com/flyway/flyway/pull/740
https://github.com/flyway/flyway/pull/743

I tested the site in jekyll on my computer, and it looks okay to me. However, please let me know if I missed anything :)

### CODE REVIEW

**Comment by axelfontaine** [comment]
Awesome work Nathan! Looks great!

**Comment by axelfontaine** [comment]
Could you also add Vertica and Redshift info to http://flywaydb.org/contribute/code/database.html ?

Cheers
Axel

**Comment by nathanvick** [comment]
Axel, I added Vertica and Redshift setup info to http://flywaydb.org/contribute/code/database.html, as requested.

**Comment by awinder** [comment]
Sorry if this is the wrong place but -- wanted to test this out and had problems following the documentation with autodetection of the flyway driver:

```
flyway-0-SNAPSHOT awinder$ ./flyway migrate
/usr/bin/tput
Flyway (Command-line Tool) v.0-SNAPSHOT

ERROR: Unable to autodetect Jdbc driver for url: jdbc:vertica://127.0.0.1:5433/testing
ERROR: Caused by: org.flywaydb.core.api.FlywayException: Unable to autodetect Jdbc driver for url: jdbc:vertica://127.0.0.1:5433/testing
ERROR: Occured in org.flywaydb.core.internal.util.jdbc.DriverDataSource.<init>() at line 103
```

(I did a build of your fork, so it should have the vertica additions in it).  I added the vertica-jdbc.jar to the maven repo like you detailed but still seems to be a problem.  Any ideas?

**Comment by nathanvick** [comment]
awinder,

My fork has two branches: vertica and redshift. If you built from master, it won't work because my master branch just reflects what I have pulled from the upstream master branch.

Also, when running from the command line, you need to put the Vertica JDBC driver in the jars folder.

**Comment by nathanvick** [comment]
Axel,

Is there anything remaining that I need to do before you can merge the Vertica and Redshift support from my fork?

**Comment by awinder** [comment]
Thanks Nathan I built the vertica branch and messed with it today and was able to successfully run some migrations and tear them down, including adding projections. I can definitely +1 this awesome addition to flyway :-)

**Comment by axelfontaine** [comment]
Great work! Merged.

**Pull request merged**
