### PR TITLE
Mentions ToPIA in "Other Tools & Frameworks" in documentation

### PR DESCRIPTION
**Pull request by ghost**
ToPIA is an model-driven development platform that comes with a persistence module, taking your UML classes models and generating a persistence layer for any relational DB (entities as POJO + some DAO). The API is extensible and ToPIA comes with a bundled plug-and-play service that plug flyway to the ToPIA API so ToPIA, while starting will call flyway at the good time: it's quick-and-easy integration.

### CODE REVIEW

**Comment by axelfontaine** [comment]
That link appears to be offline. Also please add a description in this issue of what this is.

**Comment by ghost** [comment]
Hi @axelfontaine we are working on it that's why I've marked this PR as WIP.

**Comment by ghost** [comment]
Fixed the links

**Comment by ghost** [comment]
sorry @axelfontaine for submitting a not-yet-actuality-ready PR, is everything OK with our PR now? Feel free to request any fix : we at @codelutin would be happy to see ToPIA mentioned on the site. Thanks!

**Comment by axelfontaine** [comment]
@numero-six No worries. Note that the default table name has changed in Flyway 5.0, so you may want to update that in your docs.

**Comment by ghost** [comment]
Thanks for your feedback, ToPIA still relies on Flyway 4 but I've [mentioned that in the issue](https://gitlab.nuiton.org/nuiton/topia/issues/657), good point!

**Pull request merged**
