### PR TITLE
Updated documentation for db2 z/OS to standard values

### PR DESCRIPTION
**Pull request by cteig**
Hi,

Updated the documentation for DB2 z/OS according to changes in #1210

Christine

### CODE REVIEW

**Comment by axelfontaine** [comment]
Is this still relevant or should it be closed?

**Comment by cteig** [comment]
Hi,

It is still relevant to update the documentation, but the change in documentation should be adapted to the changes in #1237
Shall I update this pull request, or make a new one for 4.1?

Christine

**Comment by axelfontaine** [comment]
Please update this one. This can go straight in the main docs once 4.0.1 is released.

Cheers
Axel

**Comment by axelfontaine** [comment]
@cteig What is it that still needs to be done here?

**Comment by axelfontaine** [comment]
Closing old pull request due to lack of response

**Pull request closed without merging**
