### PR TITLE
Build artefacts for sbt 1.0.x

### PR DESCRIPTION
**Pull request by davidmweber**
Artefacts needed for the sbt 1.0 migration of flyway-sbt. It is a build of https://github.com/flyway/flyway-sbt after discussions with @axelfontaine.

### CODE REVIEW

**Comment by jarreds** [comment]
Nice, thank you.

**Comment by davidmweber** [comment]
Is there any chance we can get this released? There is a growing group of people who are blocked because Play has moved to sbt 1.0. Thanks!

**Comment by davidmweber** [comment]
@axelfontaine Can we get some progress here? My alternative is to publish this via my own channels (probably on github pages like this PR).

**Comment by davidmweber** [comment]
I have set up an interim repo at https://davidmweber.github.io/flyway-sbt.repo/

**Comment by axelfontaine** [comment]
@davidmweber I moved the SBT section to 3rd party plugins. It would be great if you could set up your own docs either as part of this repo's wiki, or under your own URL. This way you won't be dependent on us merging changes to update them. Let me know once you have something set up, so I can link to them from the official site.

**Comment by davidmweber** [comment]
Will do.

**Pull request closed without merging**
