### PR TITLE
Add a Beta page with links to download the Beta

### PR DESCRIPTION
**Pull request by DoodleBobBuffPants**

### CODE REVIEW

**Comment by DoodleBobBuffPants** [comment]
Screenshot of the page
image

**Comment by Barry-RG** [comment]
Its probably also an idea to add the maven changes here as well

**Review by Barry-RG — APPROVED** [review]

**Comment by angellaa** [comment]
Do we want to say currently the feature is available in Flyway Teams and RG Deploy? (same words we shared in other pages?)

**Comment by angellaa** [comment]
"This feature will be available in future products, but during the beta phase you can access it through your Flyway Teams or Redgate Deploy license."

**Review by angellaa — APPROVED** [review]

**Comment by DoodleBobBuffPants** [comment]
> "This feature will be available in future products, but during the beta phase you can access it through your Flyway Teams or Redgate Deploy license."

Done in latest commit

**Pull request merged**
